### ISSUE TITLE
'uint8_t' does not name a type

### ISSUE THREAD

**Issue by matsujirushi** [FreeRTOS/FreeRTOS-Cellular-Interface#50] opened 2021-11-04 04:55 UTC
Hi,
I got these errors when my code include cellular library headers only.

**Incude:**
```
#include <cellular_config.h>
#include <cellular_config_defaults.h>
#include <cellular_comm_interface.h>
```

**Error:**
```
../Lib/FreeRTOS-Cellular-Interface/source/include/cellular_types.h:416:5: error: 'uint8_t' does not name a type
```

I think it would be better to include stdint.h here.
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/blob/main/source/include/cellular_types.h#L39

**Comment by chinglee-iot** [comment] 2021-11-04 10:04
Thank you for the feedback. I will fix this ASAP.

**Comment by chinglee-iot** [comment] 2021-11-05 03:04
The issue is fixed in this PR. Once it is merged I will close this issue.
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/pull/53

**Closed** 2021-11-07 09:05 UTC
